# -*- coding: utf-8 -*-
"""Script_A.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xmvACbYTD9UWiXPxCc3bbfyXh6d-5t9E
"""

import pandas as pd
import numpy as np
from pathlib import Path

from google.colab import drive
drive.mount('/content/drive')

MERGED_PATH = Path("/content/drive/.....merged_raw.csv")  ## Add the output path of the Data preprocessing
OUT_DIR     = Path("/content/drive/....")                ## Add the output path for Script A
OUT_DIR.mkdir(parents=True, exist_ok=True) 

G = 9.81

"""## STEP 2 - Noise filtering"""

from scipy.signal import medfilt

# ---------- causal median filter (trailing window) ----------
def causal_median_filter(x, window=5):
    return pd.Series(x).rolling(window=window, min_periods=1).median().values

# ---------- causal 1D Kalman filter ----------
class CausalKalman1D:
    def __init__(self, process_noise=1e-4, measurement_noise=1e-2, initial_value=0.0):
        self.q = process_noise
        self.r = measurement_noise
        self.x = initial_value
        self.p = 1.0

    def update(self, measurement):
        self.p += self.q                          # predict
        k = self.p / (self.p + self.r)             # Kalman gain
        self.x = self.x + k * (measurement - self.x)
        self.p = (1 - k) * self.p
        return self.x

    def filter_sequence(self, signal):
        return np.array([self.update(v) for v in signal])

# ---------- estimate real measurement noise from known-stationary trips ----------
def estimate_measurement_noise(df_all, stationary_trip_ids=("S-Vw1.csv", "S-Vw15.csv")):
    """
    V-Vw1/V-Vw15 are explicitly labeled 'Stationary (No Motion, sensor bias
    estimation)' in the README -- real variance during these trips is the
    actual sensor noise floor, not a guessed constant.
    """
    cols = ["acc_x_raw", "acc_y_raw", "acc_z_raw", "gyro_x_raw", "gyro_y_raw", "gyro_z_raw"]
    subset = df_all[df_all["trip_id"].isin(stationary_trip_ids)]
    if len(subset) < 50:
        print("[warn] stationary trips not found/too short -- falling back to default noise=1e-2")
        return {c: 1e-2 for c in cols}
    variances = subset[cols].var().to_dict()
    print("Estimated measurement noise (variance) per axis:", variances)
    return variances

# ---------- Step 2: stacked median -> Kalman, per axis ----------
def apply_noise_filtering(acc, gyro, noise_est):
    acc_cols  = ["acc_x_raw", "acc_y_raw", "acc_z_raw"]
    gyro_cols = ["gyro_x_raw", "gyro_y_raw", "gyro_z_raw"]

    acc_filt = np.zeros_like(acc)
    gyro_filt = np.zeros_like(gyro)

    for i, col in enumerate(acc_cols):
        med = causal_median_filter(acc[:, i], window=5)
        kf = CausalKalman1D(process_noise=1e-4, measurement_noise=noise_est[col], initial_value=med[0])
        acc_filt[:, i] = kf.filter_sequence(med)

    for i, col in enumerate(gyro_cols):
        med = causal_median_filter(gyro[:, i], window=5)
        kf = CausalKalman1D(process_noise=1e-4, measurement_noise=noise_est[col], initial_value=med[0])
        gyro_filt[:, i] = kf.filter_sequence(med)

    return acc_filt, gyro_filt

"""## STEP 3 - Mount calibration (REPLACED: closed-form batch calibration using ground truth, not a real-time IMU-only MEKF)
The original `AutomaticMountCalibrationEngine` was a recursive, real-time filter designed for a phone with no ground truth to check itself against. This is offline batch preprocessing and the dataset already has synchronized `veh_Velocity`/`veh_YawRate`/GPS, so orientation is solved once per trip in closed form instead:
- **Pitch/roll**: gravity can only ever fix 2 of 3 orientation angles (not yaw), so average the gravity direction over every ground-truth-stationary sample in the trip and align it to vehicle-up.
- **Yaw**: the old PCA-based one-shot lock had a 180-degree sign ambiguity and never corrected itself if wrong (see Check 3/4 -- correlated seesaw x/y = wrong-yaw signature). Instead, fit yaw directly against ground truth: reconstruct true forward acceleration from `d(veh_Velocity)/dt` and true lateral/centripetal acceleration from `veh_YawRate * veh_Velocity`, then solve for the rotation angle that best aligns the phone's horizontal acceleration to that signal (closed-form least-squares, no sign ambiguity, uses the whole trip's turns instead of one early window).
"""

def rotation_from_vectors(a, b):
    """
    Minimal-rotation matrix R such that R @ a_hat = b_hat (Rodrigues' formula for
    aligning two unit vectors). No rotation is applied about the b-axis -- when
    b = vehicle-up, this fixes pitch/roll only; yaw is solved separately below,
    since gravity alone can never determine heading.
    """
    a = np.asarray(a, dtype=float); a = a / np.linalg.norm(a)
    b = np.asarray(b, dtype=float); b = b / np.linalg.norm(b)
    v = np.cross(a, b)
    c = np.dot(a, b)
    s = np.linalg.norm(v)
    if s < 1e-8:
        if c > 0:
            return np.eye(3)
        # a and b point opposite ways -- 180-degree flip about any perpendicular axis
        perp = np.array([1.0, 0.0, 0.0]) if abs(a[0]) < 0.9 else np.array([0.0, 1.0, 0.0])
        axis = np.cross(a, perp); axis = axis / np.linalg.norm(axis)
        vx = np.array([[0, -axis[2], axis[1]], [axis[2], 0, -axis[0]], [-axis[1], axis[0], 0]])
        return np.eye(3) + 2 * (vx @ vx)
    vx = np.array([[0, -v[2], v[1]], [v[2], 0, -v[0]], [-v[1], v[0], 0]])
    return np.eye(3) + vx + vx @ vx * ((1 - c) / (s ** 2))


def calibrate_trip_orientation(acc_filt, veh_speed_kmh, veh_yaw_rate_dps, t, zupt_labels,
                                min_moving_samples=10):
    """
    REPLACES AutomaticMountCalibrationEngine entirely: one closed-form orientation
    solve per trip instead of a recursive per-sample MEKF.

    Pitch/roll: mean gravity direction over ALL ground-truth-stationary samples in
    the trip (not just the first window), aligned to vehicle-up via
    rotation_from_vectors.

    Yaw: closed-form least-squares rotation angle aligning the phone's leveled
    horizontal acceleration to the true vehicle-frame acceleration reconstructed
    from veh_Velocity (forward accel, finite difference) and
    veh_YawRate * veh_Velocity (centripetal/lateral accel). This is the standard
    2D Procrustes/Kabsch rotation-angle solution: psi = atan2(cross_sum, dot_sum).

    Returns (R_total, yaw_offset_rad, n_stationary_samples, n_moving_samples).
    """
    stat_mask = zupt_labels == 1
    if stat_mask.sum() >= 5:
        g_body = acc_filt[stat_mask].mean(axis=0)
    else:
        g_body = acc_filt.mean(axis=0)  # trip never truly stops -- fall back to overall mean
    R_pr = rotation_from_vectors(g_body, np.array([0.0, 0.0, 1.0]))

    acc_level = (R_pr @ acc_filt.T).T  # gravity-aligned, yaw still unknown
    v_mps = np.asarray(veh_speed_kmh, dtype=float) / 3.6
    a_fwd_gt = np.gradient(v_mps, t)
    a_lat_gt = np.radians(veh_yaw_rate_dps) * v_mps

    move_mask = zupt_labels == 0
    n_moving = int(move_mask.sum())
    if n_moving >= min_moving_samples:
        u = acc_level[move_mask, :2]
        w = np.column_stack([a_fwd_gt[move_mask], a_lat_gt[move_mask]])
        dot_sum = np.sum(u[:, 0] * w[:, 0] + u[:, 1] * w[:, 1])
        cross_sum = np.sum(u[:, 0] * w[:, 1] - u[:, 1] * w[:, 0])
        psi = np.arctan2(cross_sum, dot_sum)
    else:
        psi = 0.0  # not enough moving samples to determine yaw -- leave un-rotated

    cy, sy = np.cos(psi), np.sin(psi)
    R_yaw = np.array([[cy, -sy, 0.0], [sy, cy, 0.0], [0.0, 0.0, 1.0]])
    R_total = R_yaw @ R_pr
    return R_total, psi, int(stat_mask.sum()), n_moving

"""## STEP 5 - ZUPT (causal, trailing-window variance)"""

# NOTE: superseded as the ZUPT source -- kept only for reference/diagnostics.
# See STEP 5c below: ZUPT is now derived from ground-truth veh_Velocity instead,
# since acceleration variance can't distinguish zero velocity from constant velocity.
def compute_zupt_buffered(acc_buf, gyro_buf, acc_thresh, gyro_thresh):
    # NOTE: thresholds are now REQUIRED args -- see STEP 5b calibration below.
    # (previously hardcoded acc_thresh=0.035, gyro_thresh=0.0012, which was
    # never validated and caused ZUPT to false-fire during real motion)
    if len(acc_buf) < 5:
        return 0
    acc_var = np.var(np.linalg.norm(np.array(acc_buf), axis=1))
    gyro_var = np.sum(np.var(np.array(gyro_buf), axis=0))
    return int(acc_var < acc_thresh and gyro_var < gyro_thresh)

"""### STEP 5b - Empirical ZUPT threshold calibration
The hardcoded `acc_thresh=0.035`, `gyro_thresh=0.0012` were never validated against the **filtered** signal's own variance -- Check 5/6 showed ZUPT false-firing during real motion (e.g. cruising at 40-50 km/h), which corrupts gyro-bias/NHC updates and gravity removal downstream. This derives thresholds from the actual filtered-signal variance distribution on the known-stationary trips, and sanity-checks them against known-moving trips.
"""

# NOTE: diagnostic-only from here on -- its output (ZUPT_ACC_THRESH/GYRO_THRESH) is
# no longer used to build final ZUPT labels (see STEP 5c below). Kept so you can
# still compare the accelerometer-heuristic vs ground-truth-speed approaches.
import matplotlib.pyplot as plt

def _rolling_zupt_stats(trip_id, df_all, noise_est, window=5):
    """Reproduce the exact trailing-window buffering used in process_trip, on the
    filtered signal, and return the per-sample acc/gyro variances compute_zupt_buffered
    would see."""
    tdf = df_all[df_all["trip_id"] == trip_id].sort_values("t_rel_phone")
    acc_raw = tdf[["acc_x_raw", "acc_y_raw", "acc_z_raw"]].values
    gyro_raw = tdf[["gyro_x_raw", "gyro_y_raw", "gyro_z_raw"]].values
    acc_filt, gyro_filt = apply_noise_filtering(acc_raw, gyro_raw, noise_est)

    acc_vars, gyro_vars = [], []
    acc_buf, gyro_buf = [], []
    for i in range(len(tdf)):
        acc_buf.append(acc_filt[i]); gyro_buf.append(gyro_filt[i])
        if len(acc_buf) > window:
            acc_buf.pop(0); gyro_buf.pop(0)
        if len(acc_buf) < window:
            continue
        acc_vars.append(np.var(np.linalg.norm(np.array(acc_buf), axis=1)))
        gyro_vars.append(np.sum(np.var(np.array(gyro_buf), axis=0)))
    return np.array(acc_vars), np.array(gyro_vars)


def calibrate_zupt_thresholds(df_all, noise_est,
                               stationary_ids=("S-Vw1.csv", "S-Vw15.csv"),
                               moving_check_ids=("S-Vta5.csv", "S-M.csv"),
                               window=5, acc_pct=95, gyro_pct=95, plot=True):
    stat_acc = np.concatenate([_rolling_zupt_stats(t, df_all, noise_est, window)[0] for t in stationary_ids])
    stat_gyro = np.concatenate([_rolling_zupt_stats(t, df_all, noise_est, window)[1] for t in stationary_ids])

    acc_thresh = float(np.percentile(stat_acc, acc_pct))
    gyro_thresh = float(np.percentile(stat_gyro, gyro_pct))

    print(f"[ZUPT calibration] window={window}, percentile={acc_pct}/{gyro_pct}")
    print(f"  stationary acc_var:  min={stat_acc.min():.5f} median={np.median(stat_acc):.5f} "
          f"p{acc_pct}={acc_thresh:.5f} max={stat_acc.max():.5f}")
    print(f"  stationary gyro_var: min={stat_gyro.min():.6f} median={np.median(stat_gyro):.6f} "
          f"p{gyro_pct}={gyro_thresh:.6f} max={stat_gyro.max():.6f}")
    print(f"  --> NEW thresholds: acc_thresh={acc_thresh:.5f}, gyro_thresh={gyro_thresh:.6f} "
          f"(OLD hardcoded: acc_thresh=0.035, gyro_thresh=0.0012)")

    mov_stats = {}
    for tid in moving_check_ids:
        mav, mgv = _rolling_zupt_stats(tid, df_all, noise_est, window)
        false_zupt_old = np.mean((mav < 0.035) & (mgv < 0.0012))
        false_zupt_new = np.mean((mav < acc_thresh) & (mgv < gyro_thresh))
        mov_stats[tid] = (mav, mgv)
        print(f"  {tid}: false-ZUPT rate  OLD={false_zupt_old*100:5.2f}%   NEW={false_zupt_new*100:5.2f}%")

    if plot:
        fig, axes = plt.subplots(1, 2, figsize=(13, 4))
        axes[0].hist(stat_acc, bins=60, alpha=0.5, label="stationary", density=True)
        for tid, (mav, _) in mov_stats.items():
            axes[0].hist(mav, bins=60, alpha=0.4, label=f"moving: {tid}", density=True)
        axes[0].axvline(acc_thresh, color="red", linestyle="--", label="new acc_thresh")
        axes[0].axvline(0.035, color="black", linestyle=":", label="old acc_thresh")
        axes[0].set_xscale("log"); axes[0].set_title("acc rolling-variance distribution"); axes[0].legend(fontsize=7)

        axes[1].hist(stat_gyro, bins=60, alpha=0.5, label="stationary", density=True)
        for tid, (_, mgv) in mov_stats.items():
            axes[1].hist(mgv, bins=60, alpha=0.4, label=f"moving: {tid}", density=True)
        axes[1].axvline(gyro_thresh, color="red", linestyle="--", label="new gyro_thresh")
        axes[1].axvline(0.0012, color="black", linestyle=":", label="old gyro_thresh")
        axes[1].set_xscale("log"); axes[1].set_title("gyro rolling-variance distribution"); axes[1].legend(fontsize=7)
        plt.tight_layout(); plt.show()

    return acc_thresh, gyro_thresh

"""### STEP 5c - ZUPT from ground-truth vehicle speed (this is what's actually used)
Accelerometer-variance ZUPT (STEP 5/5b) cannot tell "zero velocity" apart from "constant velocity" -- both look like near-zero acceleration, which is why Check 5/6 got worse after threshold tuning, not better. This dataset has synchronized ground-truth `veh_Velocity`, so ZUPT is derived directly from it instead. (A real IMU-only ZUPT detector would only be needed for on-phone deployment, not for this offline training-data pipeline.)
"""

ZUPT_SPEED_THRESH_KMH = 2.0  # vehicle considered stationary below this speed

# (histogram of veh_Velocity is plotted in Check 5/6 below, after df_all is loaded)

def compute_zupt_from_speed(veh_speed_kmh, thresh_kmh=ZUPT_SPEED_THRESH_KMH):
    return (np.asarray(veh_speed_kmh) < thresh_kmh).astype(int)

"""### Per-trip processing (single causal pass, stateful) & STEP 4 Included"""

def process_trip(tdf, noise_est, zupt_speed_thresh_kmh=ZUPT_SPEED_THRESH_KMH):
    tdf = tdf.sort_values("t_rel_phone").reset_index(drop=True)
    t = tdf["t_rel_phone"].values
    acc_raw = tdf[["acc_x_raw", "acc_y_raw", "acc_z_raw"]].values
    gyro_raw = tdf[["gyro_x_raw", "gyro_y_raw", "gyro_z_raw"]].values
    veh_speed = tdf["veh_Velocity"].values
    veh_yaw_rate = tdf["veh_YawRate"].values

    acc_filt, gyro_filt = apply_noise_filtering(acc_raw, gyro_raw, noise_est)  # Step 2

    n = len(tdf)
    zupt_labels = compute_zupt_from_speed(veh_speed, zupt_speed_thresh_kmh)  # STEP 5c: ground-truth ZUPT

    # STEP 3 (REPLACED): one closed-form orientation calibration for the whole trip,
    # using ground truth instead of a real-time IMU-only MEKF.
    R_total, yaw_offset_rad, n_stat, n_moving = calibrate_trip_orientation(
        acc_filt, veh_speed, veh_yaw_rate, t, zupt_labels
    )
    yaw_ok = n_moving >= 10

    acc_veh = (R_total @ acc_filt.T).T - np.array([0.0, 0.0, G])  # Step 4: gravity removal, vectorized

    out = pd.DataFrame({
        "t_rel_phone": tdf["t_rel_phone"].values,
        "acc_x_veh": acc_veh[:, 0], "acc_y_veh": acc_veh[:, 1], "acc_z_veh": acc_veh[:, 2],
        "gyro_x_filt": gyro_filt[:, 0], "gyro_y_filt": gyro_filt[:, 1], "gyro_z_filt": gyro_filt[:, 2],
        "zupt_label": zupt_labels,
        "yaw_calibrated": np.full(n, yaw_ok),
        "yaw_offset_deg": np.full(n, np.degrees(yaw_offset_rad)),
        "n_stationary_samples": np.full(n, n_stat),
        "n_moving_samples": np.full(n, n_moving),
        "veh_Velocity": tdf["veh_Velocity"].values,
        "veh_Latitude": tdf["veh_Latitude"].values,
        "veh_Longitude": tdf["veh_Longitude"].values,
        "veh_YawRate": tdf["veh_YawRate"].values,
        "veh_GPS_Satellites": tdf["veh_GPS_Satellites"].values,
        "trip_id": tdf["trip_id"].values,
    })
    return out

# ============================================================
# Run over all trips
# ============================================================
df_all = pd.read_csv(MERGED_PATH)
print("Loaded:", df_all.shape, "trips:", df_all["trip_id"].nunique())

noise_est = estimate_measurement_noise(df_all)   # run ONCE, using df_all (all trips)

all_processed = []
for trip_id, tdf in df_all.groupby("trip_id"):
    print("Processing:", trip_id)
    all_processed.append(process_trip(tdf, noise_est, ZUPT_SPEED_THRESH_KMH))

final_df = pd.concat(all_processed, ignore_index=True)
final_df.to_csv(OUT_DIR / "script_a_clean_continuous.csv", index=False)
print(f"\nSaved {len(final_df)} rows to {OUT_DIR / 'script_a_clean_continuous.csv'}")

print(final_df.groupby("trip_id")["yaw_calibrated"].mean().sort_values())

"""### Checks"""

calib_summary = final_df.groupby("trip_id").agg(
    yaw_offset_deg=("yaw_offset_deg", "first"),
    yaw_calibrated=("yaw_calibrated", "first"),
    n_stationary_samples=("n_stationary_samples", "first"),
    n_moving_samples=("n_moving_samples", "first"),
    zupt_frac=("zupt_label", "mean"),
).sort_values("zupt_frac")
print(calib_summary.to_string())

# Checking stationary trips
for trip_id in ["S-Vw1.csv", "S-Vw15.csv"]:
    sub = final_df[final_df["trip_id"] == trip_id]
    print(trip_id, "| ZUPT fraction:", sub["zupt_label"].mean(),
          "| yaw_offset_deg:", sub["yaw_offset_deg"].iloc[0],
          "| yaw_calibrated:", sub["yaw_calibrated"].iloc[0])

"""## VERIFICATION CHECKS — Script A pipeline sanity
Run these after the main pipeline above (they use `df_all`, `final_df`, `noise_est`, `apply_noise_filtering`, `G`, `flip_counts`).
"""

import matplotlib.pyplot as plt

CHECK_TRIP = "S-Vta5.csv"
tdf_check = df_all[df_all["trip_id"] == CHECK_TRIP].sort_values("t_rel_phone").reset_index(drop=True)
t_check = tdf_check["t_rel_phone"].values
acc_raw_check = tdf_check[["acc_x_raw","acc_y_raw","acc_z_raw"]].values
gyro_raw_check = tdf_check[["gyro_x_raw","gyro_y_raw","gyro_z_raw"]].values
acc_filt_check, gyro_filt_check = apply_noise_filtering(acc_raw_check, gyro_raw_check, noise_est)

fig, axes = plt.subplots(3, 2, figsize=(14, 9), sharex=True)
acc_labels = ["acc_x", "acc_y", "acc_z"]
gyro_labels = ["gyro_x", "gyro_y", "gyro_z"]
for i in range(3):
    axes[i,0].plot(t_check, acc_raw_check[:,i], alpha=0.4, label="raw")
    axes[i,0].plot(t_check, acc_filt_check[:,i], label="filtered", linewidth=1.2)
    axes[i,0].set_ylabel(acc_labels[i]); axes[i,0].legend(fontsize=8)
    axes[i,1].plot(t_check, gyro_raw_check[:,i], alpha=0.4, label="raw")
    axes[i,1].plot(t_check, gyro_filt_check[:,i], label="filtered", linewidth=1.2)
    axes[i,1].set_ylabel(gyro_labels[i]); axes[i,1].legend(fontsize=8)
axes[2,0].set_xlabel("t_rel_phone (s)"); axes[2,1].set_xlabel("t_rel_phone (s)")
fig.suptitle(f"CHECK 1: Raw vs Filtered IMU -- {CHECK_TRIP} (filtered should be smoother, not lagged/distorted)")
plt.tight_layout(); plt.show()

# CHECK 2: are the two trips used to estimate sensor noise actually stationary?
fig, axes = plt.subplots(1, 2, figsize=(12,4))
for ax, tid in zip(axes, ["S-Vw1.csv", "S-Vw15.csv"]):
    sub = df_all[df_all["trip_id"] == tid].sort_values("t_rel_phone")
    acc_norm = np.linalg.norm(sub[["acc_x_raw","acc_y_raw","acc_z_raw"]].values, axis=1)
    ax.plot(sub["t_rel_phone"], acc_norm)
    ax.axhline(G, color="red", linestyle="--", label=f"G={G}")
    ax.set_title(f"{tid} -- |acc_raw| (should hover near G if truly stationary)")
    ax.set_xlabel("t_rel_phone (s)"); ax.legend()
plt.tight_layout(); plt.show()

# CHECK 3: gravity removal -- acc_veh should have z-axis hovering near 0
CHECK_TRIP2 = "S-Vta5.csv"
g_chk = final_df[final_df["trip_id"] == CHECK_TRIP2].sort_values("t_rel_phone")
fig, ax = plt.subplots(figsize=(14,4))
ax.plot(g_chk["t_rel_phone"], g_chk["acc_x_veh"], label="acc_x_veh", alpha=0.8)
ax.plot(g_chk["t_rel_phone"], g_chk["acc_y_veh"], label="acc_y_veh", alpha=0.8)
ax.plot(g_chk["t_rel_phone"], g_chk["acc_z_veh"], label="acc_z_veh (should hover ~0)", alpha=0.8)
ax.axhline(0, color="black", linewidth=0.8)
ax.set_title(f"CHECK 3: Gravity-removed vehicle-frame acceleration -- {CHECK_TRIP2}")
ax.set_xlabel("t_rel_phone (s)"); ax.legend()
plt.tight_layout(); plt.show()
print("acc_z_veh stats:\n", g_chk["acc_z_veh"].describe())

# CHECK 4 (updated for the new batch calibration): the old per-sample
# yaw_calibrated flip-counting no longer applies (orientation is now solved once
# per trip). Instead, sanity-check the fitted yaw_offset_deg: it should cluster
# reasonably tightly if the phone mount yaw is roughly consistent trip-to-trip,
# and NOT be systematically different for trips flagged yaw_calibrated=False.
calib = final_df.groupby("trip_id").agg(
    yaw_offset_deg=("yaw_offset_deg", "first"),
    yaw_calibrated=("yaw_calibrated", "first"),
).sort_values("yaw_offset_deg")

fig, axes = plt.subplots(2, 1, figsize=(14, 7))
axes[0].hist(calib["yaw_offset_deg"], bins=30)
axes[0].set_title("CHECK 4a: distribution of fitted yaw_offset_deg across all trips")
axes[0].set_xlabel("yaw_offset_deg")

colors = calib["yaw_calibrated"].map({True: "tab:blue", False: "tab:red"})
axes[1].bar(range(len(calib)), calib["yaw_offset_deg"], color=colors)
axes[1].set_xticks(range(len(calib))); axes[1].set_xticklabels(calib.index, rotation=90, fontsize=6)
axes[1].set_title("CHECK 4b: per-trip yaw_offset_deg (red = not enough moving samples to fit yaw)")
axes[1].set_ylabel("yaw_offset_deg")
plt.tight_layout(); plt.show()

# CHECK 5 (most important): does ZUPT actually fire only when the vehicle is stopped?
fig, axes = plt.subplots(2, 1, figsize=(14,7))
for ax, tid in zip(axes, ["S-Vta5.csv", "S-M.csv"]):
    g_chk = final_df[final_df["trip_id"] == tid].sort_values("t_rel_phone")
    ax2 = ax.twinx()
    ax.plot(g_chk["t_rel_phone"], g_chk["veh_Velocity"], color="tab:blue", label="veh_Velocity (km/hr)")
    ax2.fill_between(g_chk["t_rel_phone"], g_chk["zupt_label"], color="tab:red", alpha=0.3, step="post")
    ax.set_title(f"CHECK 5: ZUPT (red fill) vs ground-truth speed (blue) -- {tid}")
    ax.set_ylabel("veh_Velocity"); ax2.set_ylabel("zupt_label"); ax.set_xlabel("t_rel_phone (s)")
plt.tight_layout(); plt.show()

# Quantitative mismatch: ZUPT fired while moving fast, or missed while truly stopped
mismatch = final_df[((final_df["zupt_label"]==1) & (final_df["veh_Velocity"] > 5)) |
                     ((final_df["zupt_label"]==0) & (final_df["veh_Velocity"] < 0.5))]
print(f"ZUPT/speed mismatch rows: {len(mismatch)} / {len(final_df)} ({100*len(mismatch)/len(final_df):.2f}%)")
print(mismatch.groupby('trip_id').size().sort_values(ascending=False).head(15))

# ZUPT speed-threshold sanity histogram
plt.figure(figsize=(8, 4))
plt.hist(df_all["veh_Velocity"], bins=100)
plt.axvline(ZUPT_SPEED_THRESH_KMH, color="red", linestyle="--",
            label=f"ZUPT_SPEED_THRESH_KMH={ZUPT_SPEED_THRESH_KMH}")
plt.xlabel("veh_Velocity (km/hr)"); plt.ylabel("count"); plt.legend()
plt.title("veh_Velocity distribution (sanity-check the ZUPT speed threshold)")
plt.tight_layout(); plt.show()

# CHECK 6: per-trip sanity table -- residual acceleration during ZUPT should be ~0
def acc_mag_during_zupt(g):
    sub = g[g["zupt_label"] == 1]
    if len(sub) == 0:
        return np.nan
    return np.linalg.norm(sub[["acc_x_veh","acc_y_veh","acc_z_veh"]].values, axis=1).mean()

sanity = final_df.groupby("trip_id").apply(
    lambda g: pd.Series({
        "zupt_frac": g["zupt_label"].mean(),
        "yaw_calibrated_frac": g["yaw_calibrated"].mean(),
        "mean_acc_mag_during_zupt": acc_mag_during_zupt(g),
        "mean_speed_kmh": g["veh_Velocity"].mean(),
    }), include_groups=False
).sort_values("mean_acc_mag_during_zupt", ascending=False)

print("CHECK 6: Per-trip sanity table (flag rows with high mean_acc_mag_during_zupt -- should be near 0)")
print(sanity.to_string())

fig, ax = plt.subplots(figsize=(12,5))
sanity["mean_acc_mag_during_zupt"].plot(kind="bar", ax=ax)
ax.axhline(0.1, color="red", linestyle="--", label="0.1 m/s^2 flag threshold")
ax.set_title("Residual acceleration magnitude during ZUPT per trip (should be near 0 if calibration is correct)")
ax.legend(); plt.tight_layout(); plt.show()

"""### CHECK 8 - is the residual explained by ZUPT rarity/shape rather than mount-shift?
`gyro_bias` only updates during real ZUPT, and tilt-correction gain outside `recalibrating` is a fixed low 0.02/sample -- so a trip with few/short/late stops may simply never converge in time. Correlate `mean_acc_mag_during_zupt` against ZUPT fraction, trip duration, and number of distinct ZUPT episodes (contiguous stop segments, not total stopped samples).
"""

def count_zupt_episodes(g):
    z = g.sort_values("t_rel_phone")["zupt_label"].values
    if len(z) == 0:
        return 0
    starts = np.sum((z[1:] == 1) & (z[:-1] == 0))
    return int(starts + (1 if z[0] == 1 else 0))

episode_summary = final_df.groupby("trip_id").apply(
    lambda g: pd.Series({
        "trip_duration_s": g["t_rel_phone"].max() - g["t_rel_phone"].min(),
        "n_zupt_episodes": count_zupt_episodes(g),
    }), include_groups=False
)

combined2 = sanity.join(episode_summary).sort_values("mean_acc_mag_during_zupt", ascending=False)
print("CHECK 8: per-trip ZUPT shape/duration stats vs residual acceleration during ZUPT")
print(combined2.to_string())

fig, axes = plt.subplots(1, 3, figsize=(16, 5))
axes[0].scatter(combined2["zupt_frac"], combined2["mean_acc_mag_during_zupt"])
axes[0].set_xlabel("zupt_frac"); axes[0].set_ylabel("mean_acc_mag_during_zupt")
axes[0].set_title("ZUPT fraction vs residual")

axes[1].scatter(combined2["trip_duration_s"], combined2["mean_acc_mag_during_zupt"])
axes[1].set_xlabel("trip_duration_s")
axes[1].set_title("Trip duration vs residual")

axes[2].scatter(combined2["n_zupt_episodes"], combined2["mean_acc_mag_during_zupt"])
axes[2].set_xlabel("n_zupt_episodes")
axes[2].set_title("Number of distinct ZUPT episodes vs residual")
plt.tight_layout(); plt.show()

for col in ["zupt_frac", "trip_duration_s", "n_zupt_episodes"]:
    corr = combined2[col].corr(combined2["mean_acc_mag_during_zupt"])
    print(f"Correlation({col}, residual_acc) = {corr:.3f}")

"""### CHECK 10 - direct validation of the new calibration algorithm
Check 3/6 only verify a necessary condition (gravity removed near stops). This checks the actual goal: does the phone's calibrated forward/lateral acceleration (`acc_x_veh`/`acc_y_veh`) track the independently-derived ground-truth forward/lateral acceleration (from `veh_Velocity` and `veh_YawRate`)? This is the real pass/fail test for the algorithm replacement.
"""

CHECK_TRIP3 = "S-Vta5.csv"
g_chk = final_df[final_df["trip_id"] == CHECK_TRIP3].sort_values("t_rel_phone")
v_mps = g_chk["veh_Velocity"].values / 3.6
a_fwd_gt = np.gradient(v_mps, g_chk["t_rel_phone"].values)
a_lat_gt = np.radians(g_chk["veh_YawRate"].values) * v_mps

fig, axes = plt.subplots(2, 1, figsize=(14, 7), sharex=True)
axes[0].plot(g_chk["t_rel_phone"], g_chk["acc_x_veh"], label="acc_x_veh (phone, calibrated)")
axes[0].plot(g_chk["t_rel_phone"], a_fwd_gt, label="ground-truth forward accel (d(veh_Velocity)/dt)", alpha=0.7)
axes[0].set_title(f"CHECK 10a: forward acceleration -- phone vs ground truth -- {CHECK_TRIP3}")
axes[0].legend()

axes[1].plot(g_chk["t_rel_phone"], g_chk["acc_y_veh"], label="acc_y_veh (phone, calibrated)")
axes[1].plot(g_chk["t_rel_phone"], a_lat_gt, label="ground-truth lateral accel (yaw_rate * speed)", alpha=0.7)
axes[1].set_title("CHECK 10b: lateral acceleration -- phone vs ground truth")
axes[1].set_xlabel("t_rel_phone (s)"); axes[1].legend()
plt.tight_layout(); plt.show()

# Aggregate correlation per trip (should be strongly positive if calibration worked)
def fwd_lat_corr(g):
    v = g["veh_Velocity"].values / 3.6
    t_ = g["t_rel_phone"].values
    a_fwd = np.gradient(v, t_)
    a_lat = np.radians(g["veh_YawRate"].values) * v
    move = g["zupt_label"].values == 0
    if move.sum() < 10:
        return pd.Series({"corr_fwd": np.nan, "corr_lat": np.nan})
    return pd.Series({
        "corr_fwd": np.corrcoef(g["acc_x_veh"].values[move], a_fwd[move])[0, 1],
        "corr_lat": np.corrcoef(g["acc_y_veh"].values[move], a_lat[move])[0, 1],
    })

corr_table = final_df.groupby("trip_id").apply(fwd_lat_corr, include_groups=False).sort_values("corr_fwd")
print("CHECK 10c: per-trip correlation between phone-calibrated and ground-truth accel (closer to 1 = better)")
print(corr_table.to_string())
print(f"\nMean corr_fwd: {corr_table['corr_fwd'].mean():.3f}   Mean corr_lat: {corr_table['corr_lat'].mean():.3f}")