# -*- coding: utf-8 -*-
"""Script_B_Part_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKT4ETgpfxjyvlUi8qz5MHL0HUBBHxjS

# **SCRIPT B - PART-1**
"""

import pandas as pd
import numpy as np
import json
from pathlib import Path
from sklearn.preprocessing import StandardScaler

from google.colab import drive
drive.mount('/content/drive')

CLEAN_PATH = Path("/content/drive/...../script_a_clean_continuous.csv")  ## Add the output path of Script_A
OUT_DIR    = Path("/content/drive/.....")                               ## Add the output path for this script
OUT_DIR.mkdir(parents=True, exist_ok=True)

FEATURE_COLS = ["acc_x_veh", "acc_y_veh", "acc_z_veh", "gyro_x_filt", "gyro_y_filt", "gyro_z_filt"]
LABEL_COL = "veh_Velocity"
GPS_SAT_COL = "veh_GPS_Satellites"

OUTAGE_SAT_THRESHOLD = 4
WINDOW_SIZE = 50
STRIDE = 10
MAX_TRIP_SHARE = 0.25   # no single trip can supply more than 25% of a split's target rows

# ============================================================
# Load
# ============================================================
df = pd.read_csv(CLEAN_PATH)
print("Loaded:", df.shape, "trips:", df["trip_id"].nunique())

"""### 1 + 2 : GPS outage flag & Trip-level split, outage-prioritized, size-capped"""

df["gps_outage"] = (df[GPS_SAT_COL] < OUTAGE_SAT_THRESHOLD).astype(int)

trip_summary = df.groupby("trip_id").agg(
    rows=("gps_outage", "size"),
    outage_frac=("gps_outage", "mean")
).reset_index().sort_values("outage_frac", ascending=False).reset_index(drop=True)

total_rows = trip_summary["rows"].sum()
target_test = 0.15 * total_rows
target_val  = 0.15 * total_rows

def assign_split(trip_summary, target_test, target_val, max_share):
    assignments = {}
    cum_test, cum_val = 0, 0
    max_test_per_trip = max_share * target_test
    max_val_per_trip  = max_share * target_val

    for _, row in trip_summary.iterrows():
        trip, n = row["trip_id"], row["rows"]
        if cum_test < target_test and n <= max(max_test_per_trip, n if cum_test == 0 else max_test_per_trip):
            # allow the very first trip through even if it alone exceeds the cap (unavoidable for one huge trip),
            # but every trip after that must respect the cap
            if n <= max_test_per_trip or cum_test == 0:
                assignments[trip] = "test"
                cum_test += n
                continue
        if cum_val < target_val:
            if n <= max_val_per_trip or cum_val == 0:
                assignments[trip] = "val"
                cum_val += n
                continue
        assignments[trip] = "train"
    return assignments

assignments = assign_split(trip_summary, target_test, target_val, MAX_TRIP_SHARE)
trip_summary["split"] = trip_summary["trip_id"].map(assignments)

train_ids = trip_summary[trip_summary["split"] == "train"]["trip_id"].tolist()
val_ids   = trip_summary[trip_summary["split"] == "val"]["trip_id"].tolist()
test_ids  = trip_summary[trip_summary["split"] == "test"]["trip_id"].tolist()

train_df = df[df["trip_id"].isin(train_ids)].copy()
val_df   = df[df["trip_id"].isin(val_ids)].copy()
test_df  = df[df["trip_id"].isin(test_ids)].copy()

print(f"\nSplit sizes -- train: {len(train_df)} rows ({len(train_ids)} trips), "
      f"val: {len(val_df)} rows ({len(val_ids)} trips), "
      f"test: {len(test_df)} rows ({len(test_ids)} trips)")
print("Train outage %:", train_df["gps_outage"].mean() * 100)
print("Val outage %:  ", val_df["gps_outage"].mean() * 100)
print("Test outage %: ", test_df["gps_outage"].mean() * 100)

trip_summary.to_csv(OUT_DIR / "trip_split_report.csv", index=False)

"""### 3: Scale features -- fit on train only"""

scaler = StandardScaler().fit(train_df[FEATURE_COLS])

train_df[FEATURE_COLS] = scaler.transform(train_df[FEATURE_COLS])
val_df[FEATURE_COLS]   = scaler.transform(val_df[FEATURE_COLS])
test_df[FEATURE_COLS]  = scaler.transform(test_df[FEATURE_COLS])

# save scaler as plain JSON (mean/std) -- no sklearn/joblib dependency needed to reuse it
scaler_dict = {
    "feature_cols": FEATURE_COLS,
    "mean": scaler.mean_.tolist(),
    "scale": scaler.scale_.tolist()
}
with open(OUT_DIR / "scaler.json", "w") as f:
    json.dump(scaler_dict, f, indent=2)

"""### 4 + 5: Windowing per trip, exclude outage-target windows from TRAIN only"""

def make_windows(split_df, exclude_outage_targets):
    X, y, out = [], [], []
    for trip_id, tdf in split_df.groupby("trip_id"):
        tdf = tdf.sort_values("t_rel_phone")
        vals = tdf[FEATURE_COLS].values
        labels = tdf[LABEL_COL].values
        outages = tdf["gps_outage"].values
        for start in range(0, len(tdf) - WINDOW_SIZE + 1, STRIDE):
            end = start + WINDOW_SIZE
            if exclude_outage_targets and outages[end - 1] == 1:
                continue
            X.append(vals[start:end])
            y.append(labels[end - 1])
            out.append(outages[end - 1])
    return np.array(X), np.array(y), np.array(out)

X_train, y_train, out_train = make_windows(train_df, exclude_outage_targets=True)
X_val, y_val, out_val       = make_windows(val_df,   exclude_outage_targets=False)
X_test, y_test, out_test    = make_windows(test_df,  exclude_outage_targets=False)

print("\nWindowed shapes:")
print("Train:", X_train.shape, "Val:", X_val.shape, "Test:", X_test.shape)

# ============================================================
# Step 6: Save
# ============================================================
np.savez(OUT_DIR / "windowed_data.npz",
         X_train=X_train, y_train=y_train, out_train=out_train,
         X_val=X_val, y_val=y_val, out_val=out_val,
         X_test=X_test, y_test=y_test, out_test=out_test)

print(f"\nSaved windowed_data.npz, scaler.json, and trip_split_report.csv to {OUT_DIR}")